version:     "0002a--23-Sep-2022"
copyright:   "2022"
author:      "Daffa Muhammad Faizan"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/daffafaizan/os222/"
myloglink:   "/TXT/mylog.txt"
mypublickey: "/TXT/mypubkey.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
